apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - image: ghcr.io/yogendra/blue-green:latest
          name: client
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: CONFIG_JSON
              valueFrom:
                configMapKeyRef:
                  key: "config.json"
                  name: client
---
kind: Service
apiVersion: v1
metadata:
  name: client
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client
  labels:
    name: client
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  tls:
    - secretName: client-tls
      hosts:
        - client.nsxbg.cna-demo.ga
  rules:
    - host: client.nsxbg.cna-demo.ga
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: client
                port:
                  name: http
---

