apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  strategy: {}
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
<<<<<<< HEAD
      - image: ghcr.io/yogendra/nsx-alb-client:latest
        imagePullPolicy: Always
        name: nsx-alb-client
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 8080
            name: http
        volumeMounts:
        - name: config-volume
          mountPath: /usr/share/nginx/html/config
      volumes:
        - name: config-volume
          configMap:
            name: client
            items:
            - path: "demo-config.js"
              key: "demo-config.js"

=======
        - image: ghcr.io/yogendra/blue-green:latest
          name: client
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: CONFIG_JSON
              valueFrom:
                configMapKeyRef:
                  key: "config.json"
                  name: client
>>>>>>> 706100f79a529a30ae518a55fca9b49f3d6c3a51
---
kind: Service
apiVersion: v1
metadata:
  name: client
spec:
  selector:
    app: client
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client
  labels:
    name: client
    app: avi-gslb
  annotations:
    cert-manager.io/cluster-issuer: SelfSigned
spec:
  tls:
<<<<<<< HEAD
  - secretName: client-tls
    hosts:
      - client.apps.corp.local
  rules:
  - host: client.apps.corp.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: client
            port:
              name: http
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client
data:
  demo-config.js: |
    window.demoConfig = {
      "server":{
        "url": "https://echo-server.apps.corp.local"
      },
      "request": {
        "interval": 10
      },
      "graph": {
        "max": 500,
        "colors": ["blue", "green", "cyan", "orange"]
      }
    }
=======
    - secretName: client-tls
      hosts:
        - client.nsxbg.cna-demo.ga
  rules:
    - host: client.nsxbg.cna-demo.ga
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: client
                port:
                  name: http
---

>>>>>>> 706100f79a529a30ae518a55fca9b49f3d6c3a51
