apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: echo-server
    version: green
  name: echo-server-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-server
      version: green  
  template:
    metadata:
      labels:
        app: echo-server
        version: green
    spec:
      containers:
      - image: ghcr.io/yogendra/echo-server
        name: echo-server
        env:
        - name: port
          value: "8080"
        - name: CLUSTER
          value: green
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name:  echo-server-green
  labels:
    app: echo-server
    version: green
spec:
  selector:
    app:  echo-server
    version: green
  type:  ClusterIP 
  ports:
  - name:  http
    port:  80
    targetPort:  http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-server-green
  labels:
    name: echo-server
    version: green
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: echo-server-green-tls
    hosts:
      - echo-server-green.nsxbg.cna-demo.ga
  rules:
  - host: echo-server-green.nsxbg.cna-demo.ga
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: echo-server-green
            port: 
              name: http
