apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client-backed
  name: client-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-backed
  strategy: {}
  template:
    metadata:
      labels:
        app: client-backed
    spec:
      containers:
      - image: ghcr.io/yogendra/blue-green-backend:latest
        name: blue-green-backend
        resources: 
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: CONFIG_JSON
            valueFrom:
              configMapKeyRef:
                key: config
                name: client-backend
        ports:
          - containerPort: 3000
            name: http
---
kind: Service
apiVersion: v1
metadata:
  name:  client-backend
spec:
  selector:
    app: client-backend
  type: ClusterIP 
  ports:
  - name: http
    port: 80
    targetPort: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: client-backend
  labels:
    name: client-backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: contour
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: client-backend-tls
    hosts:
      - client-backend.nsxbg.cna-demo.ga
  rules:
  - host: client-backend.nsxbg.cna-demo.ga
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: client-backend
            port: 
              name: http
---
