---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client-backend
data:
  config: |
    {
      "port": 3000,
      "endpoint": {
        "address": "https://echo-server.nsxbg.cna-demo.ga",
        "type": "web",
        "versions": ["blue", "green"]
      },
      "probe": {
        "interval": 10
      },
      "sample": {
        "interval": 1000,
        "max": 600
      }
    }
