apiVersion: amko.vmware.com/v1alpha1
kind: GSLBHostRule
metadata:
  name: gslbhostrule
spec:
  fqdn: echo-server.apps.corp.local
  trafficSplit:
  - cluster: ocp-east-admin
    weight: 20
  - cluster: ocp-west-admin
    weight: 1
  ttl: 1
